# Generated by Django 3.2.3 on 2021-05-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail',
            name='document',
            field=models.FileField(default='resume', upload_to='documents'),
            preserve_default=False,
        ),
    ]
